#! /bin/bash
ssh 192.168.0.234
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-add-repository ppa:ansible/ansible -y
sudo apt-get update
sudo apt-get install ansible  -y
sudo apt-get upgrade -y
git clone https://github.com/andreipak/wordpress-ansible.git
cd wordpress-ansible
sudo ansible-playbook -i hosts playbook.yml
